!source "CIARegisters"

; Joystick Masks
JOYSTICK_N_MASK     =$1
JOYSTICK_S_MASK     =$2
JOYSTICK_W_MASK     =$4
JOYSTICK_E_MASK     =$8

JOYSTICK_NW_MASK    =JOYSTICK_N_MASK + JOYSTICK_W_MASK
JOYSTICK_NE_MASK    =JOYSTICK_N_MASK + JOYSTICK_E_MASK

JOYSTICK_SW_MASK    =JOYSTICK_S_MASK + JOYSTICK_W_MASK
JOYSTICK_SE_MASK    =JOYSTICK_S_MASK + JOYSTICK_E_MASK

JOYSTICK_FIRE_MASK  =$10



