!source "VICRegisters"
VIC_BANK_START = 0
VIC_SCREEN_ADDRESS = 1024
VIC_SCREEN_START_OFFSET = VIC_SCREEN_ADDRESS-VIC_BANK_START

; Sprite memory pointers are offset from the current Screen Address - as dictated by the VIC Bank and Memory Configuration (VIC_SPRITE_MEMORY_CONFIG)
; Memory addresses $1000-$2000 and $9000-$a000 are always interpreted as Character ROM by the VIC
VIC_SPRITE_MEMORY_POINTER_OFFSET  =$03f8

VIC_HARDWARE_SPRITE_COUNT    =8
VIC_HARDWARE_SPRITE_HEIGHT   =21
VIC_HARDWARE_SPRITE_WIDTH    =24
VIC_SPRITE_BORDER_LEFT       =24
VIC_SPRITE_BORDER_LEFT_38    =32
VIC_SPRITE_BORDER_RIGHT      =VIC_SPRITE_BORDER_LEFT+(40*8)     ; inside SPRITE_BORDER 344
VIC_SPRITE_BORDER_RIGHT_38   =VIC_SPRITE_BORDER_LEFT_38+(38*8)  ; inside SPRITE_BORDER 336
VIC_SPRITE_BORDER_TOP        =50
VIC_SPRITE_BORDER_TOP_24     =54
VIC_SPRITE_BORDER_BOTTOM     =VIC_SPRITE_BORDER_TOP+(25*8)      ; inside SPRITE_BORDER 250
VIC_SPRITE_BORDER_BOTTOM_24  =VIC_SPRITE_BORDER_TOP_24+(24*8)   ; inside SPRITE_BORDER 246

VIC_RASTER_LINES_PAL  =312
VIC_RASTER_LINES_NTSC =263

VIC_BANK_0            =$0000
VIC_BANK_1            =$4000
VIC_BANK_2            =$8000
VIC_BANK_3            =$C000



VIC_CONTROL_REGISTER_1_DEFAULT  =$1B





VIC_COLOUR_BLACK          =0
VIC_COLOUR_WHITE          =1
VIC_COLOUR_RED            =2
VIC_COLOUR_CYAN           =3
VIC_COLOUR_PURPLE         =4
VIC_COLOUR_GREEN          =5
VIC_COLOUR_BLUE           =6
VIC_COLOUR_YELLOW         =7
VIC_COLOUR_ORANGE         =8
VIC_COLOUR_BROWN          =9
VIC_COLOUR_LIGHT_RED      =10
VIC_COLOUR_DARK_GREY      =11
VIC_COLOUR_GREY           =12
VIC_COLOUR_LIGHT_GREEN    =13
VIC_COLOUR_LIGHT_BLUE     =14
VIC_COLOUR_LIGHT_GREY     =15


